import { ColumnDef } from '@tanstack/angular-table';

import { LtvValidationRow } from '../../../core/interfaces/ltv-validation.interfaces';
import type { DataTableColumnFilterConfig } from '../../../shared/components/data-table';

export const LTV_VALIDATION_COLUMN_FILTER_CONFIG: Record<string, DataTableColumnFilterConfig> =
  {
    parentLoanId: { type: 'text', placeholder: 'Search parent loan...' },
    childLoanId: { type: 'text', placeholder: 'Search child loan...' },
    loanDescription: { type: 'text', placeholder: 'Search description...' },
    loanAlias: { type: 'text', placeholder: 'Search alias...' },
    investorAlias: { type: 'text', placeholder: 'Search investor...' },
    securityValue: { type: 'text', placeholder: 'Search amount...' },
    exposure: { type: 'text', placeholder: 'Search exposure...' },
    ranking: { type: 'text', placeholder: 'Search ranking...' },
    ltv: { type: 'text', placeholder: 'Search LTV...' },
    aiCommentary: { type: 'text', placeholder: 'Search commentary...' },
    dateDwhUpdate: { type: 'date' },
  };

export const LTV_VALIDATION_COLUMNS: ColumnDef<LtvValidationRow>[] = [
  {
    id: 'parentLoanId',
    accessorKey: 'parentLoanId',
    header: 'Parent Loan ID',
    size: 120,
    minSize: 110,
    enableSorting: true,
    enableColumnFilter: true,
  },
  {
    id: 'childLoanId',
    accessorKey: 'childLoanId',
    header: 'Child Loan ID',
    size: 120,
    minSize: 110,
    enableSorting: true,
    enableColumnFilter: true,
  },
  {
    id: 'loanDescription',
    accessorKey: 'loanDescription',
    header: 'Description',
    size: 220,
    minSize: 180,
    enableSorting: true,
    enableColumnFilter: true,
  },
  {
    id: 'loanAlias',
    accessorKey: 'loanAlias',
    header: 'Loan Alias',
    size: 160,
    minSize: 140,
    enableSorting: true,
    enableColumnFilter: true,
  },
  {
    id: 'investorAlias',
    accessorKey: 'investorAlias',
    header: 'Investor Alias',
    size: 130,
    minSize: 110,
    enableSorting: true,
    enableColumnFilter: true,
  },
  {
    id: 'securityValue',
    accessorKey: 'securityValue',
    header: 'Security Value',
    size: 170,
    minSize: 150,
    enableSorting: true,
    enableColumnFilter: true,
  },
  {
    id: 'exposure',
    accessorKey: 'exposure',
    header: 'Exposure',
    size: 150,
    minSize: 130,
    enableSorting: true,
    enableColumnFilter: true,
  },
  {
    id: 'ranking',
    accessorKey: 'ranking',
    header: 'Ranking',
    size: 100,
    minSize: 90,
    enableSorting: true,
    enableColumnFilter: true,
  },
  {
    id: 'ltv',
    accessorKey: 'ltv',
    header: 'LTV',
    size: 100,
    minSize: 90,
    enableSorting: true,
    enableColumnFilter: true,
  },
  {
    id: 'aiCommentary',
    accessorKey: 'aiCommentary',
    header: 'AI Commentary',
    size: 200,
    minSize: 160,
    enableSorting: true,
    enableColumnFilter: true,
  },
  {
    id: 'dateDwhUpdate',
    accessorKey: 'dateDwhUpdate',
    header: 'Date of DWH Update',
    size: 160,
    minSize: 150,
    enableSorting: true,
    enableColumnFilter: true,
  },
];
