import { InvestorAliasRow } from '../interfaces/investor.interfaces';

/** Mock investors for Investor Alias until the live API is connected. */
export const INVESTOR_ALIAS_EXAMPLE_DATA: InvestorAliasRow[] = [
  {
    investor_key: 1001,
    investor_code: 'INV-1001',
    investor_name: 'GMF Nominee Inc',
    investor_alias_name: 'GMF Nominee',
    user_updated_date: '2026-04-16',
    user_updated_by: 'jsmith',
  },
  {
    investor_key: 1002,
    investor_code: 'INV-1002',
    investor_name: 'KingSett Real Estate Mortgage LP No. 3',
    investor_alias_name: 'KS Mortgage LP 3',
    user_updated_date: '2026-04-10',
    user_updated_by: 'alee',
  },
  {
    investor_key: 1003,
    investor_code: 'INV-1003',
    investor_name: 'CIBC World Markets',
    investor_alias_name: 'CIBC World Markets',
    user_updated_date: '2026-03-28',
    user_updated_by: 'mchen',
  },
  {
    investor_key: 1004,
    investor_code: 'INV-1004',
    investor_name: 'TD Securities',
    investor_alias_name: 'TD Securities',
    user_updated_date: '2026-03-15',
    user_updated_by: 'rkaur',
  },
  {
    investor_key: 1005,
    investor_code: 'INV-1005',
    investor_name: 'RBC Capital Markets',
    investor_alias_name: 'RBC Capital',
    user_updated_date: '2026-02-22',
    user_updated_by: 'jsmith',
  },
  {
    investor_key: 1006,
    investor_code: 'INV-1006',
    investor_name: 'BMO Capital Markets',
    investor_alias_name: 'BMO Capital Markets',
    user_updated_date: '2026-02-08',
    user_updated_by: 'alee',
  },
  {
    investor_key: 1007,
    investor_code: 'INV-1007',
    investor_name: 'National Bank',
    investor_alias_name: 'National Bank',
    user_updated_date: '2026-01-30',
    user_updated_by: 'mchen',
  },
  {
    investor_key: 1008,
    investor_code: 'INV-1008',
    investor_name: 'Scotiabank',
    investor_alias_name: 'Scotiabank',
    user_updated_date: '2026-01-18',
    user_updated_by: 'rkaur',
  },
  {
    investor_key: 1009,
    investor_code: 'INV-1009',
    investor_name: 'Manulife Financial',
    investor_alias_name: 'Manulife',
    user_updated_date: '2025-12-12',
    user_updated_by: 'jsmith',
  },
  {
    investor_key: 1010,
    investor_code: 'INV-1010',
    investor_name: 'Sun Life Financial',
    investor_alias_name: 'Sun Life',
    user_updated_date: '2025-11-30',
    user_updated_by: 'alee',
  },
  {
    investor_key: 1011,
    investor_code: 'INV-1011',
    investor_name: 'Desjardins Capital',
    investor_alias_name: 'Desjardins Capital',
    user_updated_date: '2025-11-05',
    user_updated_by: 'mchen',
  },
  {
    investor_key: 1012,
    investor_code: 'INV-1012',
    investor_name: 'HSBC Bank Canada',
    investor_alias_name: 'HSBC Canada',
    user_updated_date: '2025-10-20',
    user_updated_by: 'rkaur',
  },
  {
    investor_key: 1013,
    investor_code: 'INV-1013',
    investor_name: 'Laurentian Bank Securities',
    investor_alias_name: 'Laurentian Securities',
    user_updated_date: '2025-10-01',
    user_updated_by: 'jsmith',
  },
  {
    investor_key: 1014,
    investor_code: 'INV-1014',
    investor_name: 'Fiera Real Estate LP',
    investor_alias_name: 'Fiera RE LP',
    user_updated_date: '2025-09-14',
    user_updated_by: 'alee',
  },
  {
    investor_key: 1015,
    investor_code: 'INV-1015',
    investor_name: 'Brookfield Asset Management',
    investor_alias_name: 'Brookfield AM',
    user_updated_date: '2025-08-22',
    user_updated_by: 'mchen',
  },
  {
    investor_key: 1016,
    investor_code: 'INV-1016',
    investor_name: 'Canada Pension Plan Investment Board',
    investor_alias_name: 'CPPIB',
    user_updated_date: '2025-08-01',
    user_updated_by: 'rkaur',
  },
  {
    investor_key: 1017,
    investor_code: 'INV-1017',
    investor_name: 'Ontario Teachers Pension Plan',
    investor_alias_name: 'OTPP',
    user_updated_date: '2025-07-19',
    user_updated_by: 'jsmith',
  },
  {
    investor_key: 1018,
    investor_code: 'INV-1018',
    investor_name: 'Healthcare of Ontario Pension Plan',
    investor_alias_name: 'HOOPP',
    user_updated_date: '2025-07-02',
    user_updated_by: 'alee',
  },
  {
    investor_key: 1019,
    investor_code: 'INV-1019',
    investor_name: 'Ivanhoe Cambridge Inc',
    investor_alias_name: 'Ivanhoe Cambridge',
    user_updated_date: '2025-06-11',
    user_updated_by: 'mchen',
  },
  {
    investor_key: 1020,
    investor_code: 'INV-1020',
    investor_name: 'QuadReal Property Group',
    investor_alias_name: 'QuadReal',
    user_updated_date: '2025-05-28',
    user_updated_by: 'rkaur',
  },
  {
    investor_key: 1021,
    investor_code: 'INV-1021',
    investor_name: 'Allied Properties REIT',
    investor_alias_name: 'Allied REIT',
    user_updated_date: '2025-05-10',
    user_updated_by: 'jsmith',
  },
  {
    investor_key: 1022,
    investor_code: 'INV-1022',
    investor_name: 'RioCan Real Estate Investment Trust',
    investor_alias_name: 'RioCan REIT',
    user_updated_date: '2025-04-22',
    user_updated_by: 'alee',
  },
  {
    investor_key: 1023,
    investor_code: 'INV-1023',
    investor_name: 'Choice Properties REIT',
    investor_alias_name: 'Choice Properties',
    user_updated_date: '2025-04-03',
    user_updated_by: 'mchen',
  },
  {
    investor_key: 1024,
    investor_code: 'INV-1024',
    investor_name: 'SmartCentres Real Estate Investment Trust',
    investor_alias_name: 'SmartCentres REIT',
    user_updated_date: '2025-03-15',
    user_updated_by: 'rkaur',
  },
  {
    investor_key: 1025,
    investor_code: 'INV-1025',
    investor_name: 'Dream Industrial REIT',
    investor_alias_name: 'Dream Industrial',
    user_updated_date: '2025-02-28',
    user_updated_by: 'jsmith',
  },
  {
    investor_key: 1026,
    investor_code: 'INV-1026',
    investor_name: 'H&R Real Estate Investment Trust',
    investor_alias_name: '',
    user_updated_date: '2025-02-10',
    user_updated_by: 'alee',
  },
  {
    investor_key: 1027,
    investor_code: 'INV-1027',
    investor_name: 'Artis Real Estate Investment Trust',
    investor_alias_name: 'Artis REIT',
    user_updated_date: '2025-01-25',
    user_updated_by: 'mchen',
  },
  {
    investor_key: 1028,
    investor_code: 'INV-1028',
    investor_name: 'NorthWest Healthcare Properties REIT',
    investor_alias_name: 'NorthWest Healthcare',
    user_updated_date: '2025-01-08',
    user_updated_by: 'rkaur',
  },
];
