import { LoanApiRecord } from '../interfaces/loan.interfaces';

/** Mock loans for Loan Ranking until the live API is connected. */
export const LOANS_RANKING_EXAMPLE_DATA: LoanApiRecord[] = [
  {
    LoanKey: 'ln5037',
    LoanCode: 'ln5037',
    LoanDescription: 'Brentwood Tower C - 1st Mtg',
    LoanAliasName: 'Brentwood Tower C',
    LoanAliasOptions: 'Brentwood Tower C,Brentwood Tower B,Brentwood Tower A',
    InvestorName: 'GMF Nominee Inc',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-04-16',
    Status: 'ACTIVE',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln0398',
    LoanCode: 'ln0398',
    LoanDescription: 'KingSett Mortgage LP No. 3 - 2nd Mtg',
    LoanAliasName: 'KingSett Mortgage LP No. 3',
    LoanAliasOptions: 'KingSett Mortgage LP No. 3,KingSett Mortgage LP No. 2',
    InvestorName: 'KingSett Real Estate Mortgage LP No. 3',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Per Scott C, No Late Interest to be charged',
    UserUpdatedDate: '2026-04-10',
    Status: 'ACTIVE',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln2841',
    LoanCode: 'ln2841',
    LoanDescription: 'Harbourfront Residences - 1st Mtg',
    LoanAliasName: 'Harbourfront Residences',
    LoanAliasOptions: 'Harbourfront Residences,Harbourfront Retail',
    InvestorName: 'CIBC World Markets',
    LoanRanking: 1,
    DummyLoanIdentifier: true,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-03-28',
    Status: 'SETTLED',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln1192',
    LoanCode: 'ln1192',
    LoanDescription: 'Metro Industrial Park - Bridge',
    LoanAliasName: 'Metro Industrial Park',
    LoanAliasOptions: 'Metro Industrial Park,Metro Logistics Hub',
    InvestorName: 'TD Securities',
    LoanRanking: 3,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Standard late charge applies',
    UserUpdatedDate: '2026-03-15',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln6720',
    LoanCode: 'ln6720',
    LoanDescription: 'Yorkville Retail - 1st Mtg',
    LoanAliasName: 'Yorkville Retail',
    LoanAliasOptions: 'Yorkville Retail,Yorkville Mixed Use',
    InvestorName: 'RBC Capital Markets',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-02-22',
    Status: 'ACTIVE',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln4455',
    LoanCode: 'ln4455',
    LoanDescription: 'Scarborough Office - 2nd Mtg',
    LoanAliasName: 'Scarborough Office',
    LoanAliasOptions: 'Scarborough Office,Scarborough Plaza',
    InvestorName: 'BMO Capital Markets',
    LoanRanking: 2,
    DummyLoanIdentifier: true,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-02-08',
    Status: 'SETTLED',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln9083',
    LoanCode: 'ln9083',
    LoanDescription: 'North York Apartments - 1st Mtg',
    LoanAliasName: 'North York Apartments',
    LoanAliasOptions: 'North York Apartments,North York Tower',
    InvestorName: 'National Bank',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Waived per amendment 2025-12',
    UserUpdatedDate: '2026-01-30',
    Status: 'ACTIVE',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln3310',
    LoanCode: 'ln3310',
    LoanDescription: 'Mississauga Logistics - 1st Mtg',
    LoanAliasName: 'Mississauga Logistics',
    LoanAliasOptions: 'Mississauga Logistics,Mississauga Industrial',
    InvestorName: 'Scotiabank',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-01-18',
    Status: 'ACTIVE',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln7562',
    LoanCode: 'ln7562',
    LoanDescription: 'Oakville Medical Centre - 1st Mtg',
    LoanAliasName: 'Oakville Medical Centre',
    LoanAliasOptions: 'Oakville Medical Centre,Oakville Health Campus',
    InvestorName: 'Manulife Financial',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2025-12-05',
    Status: 'SETTLED',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln2189',
    LoanCode: 'ln2189',
    LoanDescription: 'Hamilton Mixed Use - Mezz',
    LoanAliasName: 'Hamilton Mixed Use',
    LoanAliasOptions: 'Hamilton Mixed Use,Hamilton Retail',
    InvestorName: 'Sun Life Financial',
    LoanRanking: 3,
    DummyLoanIdentifier: true,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Per Scott C, No Late Interest to be charged',
    UserUpdatedDate: '2025-11-20',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln8644',
    LoanCode: 'ln8644',
    LoanDescription: 'Waterloo Student Housing - 1st Mtg',
    LoanAliasName: 'Waterloo Student Housing',
    LoanAliasOptions: 'Waterloo Student Housing,Waterloo Campus Res',
    InvestorName: 'Desjardins Capital',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2025-10-14',
    Status: 'ACTIVE',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln5921',
    LoanCode: 'ln5921',
    LoanDescription: 'London Retail Portfolio - 2nd Mtg',
    LoanAliasName: 'London Retail Portfolio',
    LoanAliasOptions: 'London Retail Portfolio,London Mall Recap',
    InvestorName: 'HSBC Bank Canada',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Review annually',
    UserUpdatedDate: '2025-09-02',
    Status: 'SETTLED',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln5037',
    LoanCode: 'ln5037',
    LoanDescription: 'Brentwood Tower C - 1st Mtg',
    LoanAliasName: 'Brentwood Tower C',
    LoanAliasOptions: 'Brentwood Tower C,Brentwood Tower B,Brentwood Tower A',
    InvestorName: 'GMF Nominee Inc',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-04-16',
    Status: 'ACTIVE',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln0398',
    LoanCode: 'ln0398',
    LoanDescription: 'KingSett Mortgage LP No. 3 - 2nd Mtg',
    LoanAliasName: 'KingSett Mortgage LP No. 3',
    LoanAliasOptions: 'KingSett Mortgage LP No. 3,KingSett Mortgage LP No. 2',
    InvestorName: 'KingSett Real Estate Mortgage LP No. 3',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Per Scott C, No Late Interest to be charged',
    UserUpdatedDate: '2026-04-10',
    Status: 'ACTIVE',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln2841',
    LoanCode: 'ln2841',
    LoanDescription: 'Harbourfront Residences - 1st Mtg',
    LoanAliasName: 'Harbourfront Residences',
    LoanAliasOptions: 'Harbourfront Residences,Harbourfront Retail',
    InvestorName: 'CIBC World Markets',
    LoanRanking: 1,
    DummyLoanIdentifier: true,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-03-28',
    Status: 'SETTLED',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln1192',
    LoanCode: 'ln1192',
    LoanDescription: 'Metro Industrial Park - Bridge',
    LoanAliasName: 'Metro Industrial Park',
    LoanAliasOptions: 'Metro Industrial Park,Metro Logistics Hub',
    InvestorName: 'TD Securities',
    LoanRanking: 3,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Standard late charge applies',
    UserUpdatedDate: '2026-03-15',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln6720',
    LoanCode: 'ln6720',
    LoanDescription: 'Yorkville Retail - 1st Mtg',
    LoanAliasName: 'Yorkville Retail',
    LoanAliasOptions: 'Yorkville Retail,Yorkville Mixed Use',
    InvestorName: 'RBC Capital Markets',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-02-22',
    Status: 'ACTIVE',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln4455',
    LoanCode: 'ln4455',
    LoanDescription: 'Scarborough Office - 2nd Mtg',
    LoanAliasName: 'Scarborough Office',
    LoanAliasOptions: 'Scarborough Office,Scarborough Plaza',
    InvestorName: 'BMO Capital Markets',
    LoanRanking: 2,
    DummyLoanIdentifier: true,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-02-08',
    Status: 'SETTLED',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln9083',
    LoanCode: 'ln9083',
    LoanDescription: 'North York Apartments - 1st Mtg',
    LoanAliasName: 'North York Apartments',
    LoanAliasOptions: 'North York Apartments,North York Tower',
    InvestorName: 'National Bank',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Waived per amendment 2025-12',
    UserUpdatedDate: '2026-01-30',
    Status: 'ACTIVE',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln3310',
    LoanCode: 'ln3310',
    LoanDescription: 'Mississauga Logistics - 1st Mtg',
    LoanAliasName: 'Mississauga Logistics',
    LoanAliasOptions: 'Mississauga Logistics,Mississauga Industrial',
    InvestorName: 'Scotiabank',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-01-18',
    Status: 'ACTIVE',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln7562',
    LoanCode: 'ln7562',
    LoanDescription: 'Oakville Medical Centre - 1st Mtg',
    LoanAliasName: 'Oakville Medical Centre',
    LoanAliasOptions: 'Oakville Medical Centre,Oakville Health Campus',
    InvestorName: 'Manulife Financial',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2025-12-05',
    Status: 'SETTLED',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln2189',
    LoanCode: 'ln2189',
    LoanDescription: 'Hamilton Mixed Use - Mezz',
    LoanAliasName: 'Hamilton Mixed Use',
    LoanAliasOptions: 'Hamilton Mixed Use,Hamilton Retail',
    InvestorName: 'Sun Life Financial',
    LoanRanking: 3,
    DummyLoanIdentifier: true,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Per Scott C, No Late Interest to be charged',
    UserUpdatedDate: '2025-11-20',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln8644',
    LoanCode: 'ln8644',
    LoanDescription: 'Waterloo Student Housing - 1st Mtg',
    LoanAliasName: 'Waterloo Student Housing',
    LoanAliasOptions: 'Waterloo Student Housing,Waterloo Campus Res',
    InvestorName: 'Desjardins Capital',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2025-10-14',
    Status: 'ACTIVE',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln5921',
    LoanCode: 'ln5921',
    LoanDescription: 'London Retail Portfolio - 2nd Mtg',
    LoanAliasName: 'London Retail Portfolio',
    LoanAliasOptions: 'London Retail Portfolio,London Mall Recap',
    InvestorName: 'HSBC Bank Canada',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Review annually',
    UserUpdatedDate: '2025-09-02',
    Status: 'SETTLED',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln5037',
    LoanCode: 'ln5037',
    LoanDescription: 'Brentwood Tower C - 1st Mtg',
    LoanAliasName: 'Brentwood Tower C',
    LoanAliasOptions: 'Brentwood Tower C,Brentwood Tower B,Brentwood Tower A',
    InvestorName: 'GMF Nominee Inc',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-04-16',
    Status: 'ACTIVE',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln0398',
    LoanCode: 'ln0398',
    LoanDescription: 'KingSett Mortgage LP No. 3 - 2nd Mtg',
    LoanAliasName: 'KingSett Mortgage LP No. 3',
    LoanAliasOptions: 'KingSett Mortgage LP No. 3,KingSett Mortgage LP No. 2',
    InvestorName: 'KingSett Real Estate Mortgage LP No. 3',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Per Scott C, No Late Interest to be charged',
    UserUpdatedDate: '2026-04-10',
    Status: 'ACTIVE',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln2841',
    LoanCode: 'ln2841',
    LoanDescription: 'Harbourfront Residences - 1st Mtg',
    LoanAliasName: 'Harbourfront Residences',
    LoanAliasOptions: 'Harbourfront Residences,Harbourfront Retail',
    InvestorName: 'CIBC World Markets',
    LoanRanking: 1,
    DummyLoanIdentifier: true,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-03-28',
    Status: 'SETTLED',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln1192',
    LoanCode: 'ln1192',
    LoanDescription: 'Metro Industrial Park - Bridge',
    LoanAliasName: 'Metro Industrial Park',
    LoanAliasOptions: 'Metro Industrial Park,Metro Logistics Hub',
    InvestorName: 'TD Securities',
    LoanRanking: 3,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Standard late charge applies',
    UserUpdatedDate: '2026-03-15',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln6720',
    LoanCode: 'ln6720',
    LoanDescription: 'Yorkville Retail - 1st Mtg',
    LoanAliasName: 'Yorkville Retail',
    LoanAliasOptions: 'Yorkville Retail,Yorkville Mixed Use',
    InvestorName: 'RBC Capital Markets',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-02-22',
    Status: 'ACTIVE',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln4455',
    LoanCode: 'ln4455',
    LoanDescription: 'Scarborough Office - 2nd Mtg',
    LoanAliasName: 'Scarborough Office',
    LoanAliasOptions: 'Scarborough Office,Scarborough Plaza',
    InvestorName: 'BMO Capital Markets',
    LoanRanking: 2,
    DummyLoanIdentifier: true,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-02-08',
    Status: 'SETTLED',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln9083',
    LoanCode: 'ln9083',
    LoanDescription: 'North York Apartments - 1st Mtg',
    LoanAliasName: 'North York Apartments',
    LoanAliasOptions: 'North York Apartments,North York Tower',
    InvestorName: 'National Bank',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Waived per amendment 2025-12',
    UserUpdatedDate: '2026-01-30',
    Status: 'ACTIVE',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln3310',
    LoanCode: 'ln3310',
    LoanDescription: 'Mississauga Logistics - 1st Mtg',
    LoanAliasName: 'Mississauga Logistics',
    LoanAliasOptions: 'Mississauga Logistics,Mississauga Industrial',
    InvestorName: 'Scotiabank',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-01-18',
    Status: 'ACTIVE',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln7562',
    LoanCode: 'ln7562',
    LoanDescription: 'Oakville Medical Centre - 1st Mtg',
    LoanAliasName: 'Oakville Medical Centre',
    LoanAliasOptions: 'Oakville Medical Centre,Oakville Health Campus',
    InvestorName: 'Manulife Financial',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2025-12-05',
    Status: 'SETTLED',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln2189',
    LoanCode: 'ln2189',
    LoanDescription: 'Hamilton Mixed Use - Mezz',
    LoanAliasName: 'Hamilton Mixed Use',
    LoanAliasOptions: 'Hamilton Mixed Use,Hamilton Retail',
    InvestorName: 'Sun Life Financial',
    LoanRanking: 3,
    DummyLoanIdentifier: true,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Per Scott C, No Late Interest to be charged',
    UserUpdatedDate: '2025-11-20',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln8644',
    LoanCode: 'ln8644',
    LoanDescription: 'Waterloo Student Housing - 1st Mtg',
    LoanAliasName: 'Waterloo Student Housing',
    LoanAliasOptions: 'Waterloo Student Housing,Waterloo Campus Res',
    InvestorName: 'Desjardins Capital',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2025-10-14',
    Status: 'ACTIVE',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln5921',
    LoanCode: 'ln5921',
    LoanDescription: 'London Retail Portfolio - 2nd Mtg',
    LoanAliasName: 'London Retail Portfolio',
    LoanAliasOptions: 'London Retail Portfolio,London Mall Recap',
    InvestorName: 'HSBC Bank Canada',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Review annually',
    UserUpdatedDate: '2025-09-02',
    Status: 'SETTLED',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln5037',
    LoanCode: 'ln5037',
    LoanDescription: 'Brentwood Tower C - 1st Mtg',
    LoanAliasName: 'Brentwood Tower C',
    LoanAliasOptions: 'Brentwood Tower C,Brentwood Tower B,Brentwood Tower A',
    InvestorName: 'GMF Nominee Inc',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-04-16',
    Status: 'ACTIVE',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln0398',
    LoanCode: 'ln0398',
    LoanDescription: 'KingSett Mortgage LP No. 3 - 2nd Mtg',
    LoanAliasName: 'KingSett Mortgage LP No. 3',
    LoanAliasOptions: 'KingSett Mortgage LP No. 3,KingSett Mortgage LP No. 2',
    InvestorName: 'KingSett Real Estate Mortgage LP No. 3',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Per Scott C, No Late Interest to be charged',
    UserUpdatedDate: '2026-04-10',
    Status: 'ACTIVE',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln2841',
    LoanCode: 'ln2841',
    LoanDescription: 'Harbourfront Residences - 1st Mtg',
    LoanAliasName: 'Harbourfront Residences',
    LoanAliasOptions: 'Harbourfront Residences,Harbourfront Retail',
    InvestorName: 'CIBC World Markets',
    LoanRanking: 1,
    DummyLoanIdentifier: true,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-03-28',
    Status: 'SETTLED',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln1192',
    LoanCode: 'ln1192',
    LoanDescription: 'Metro Industrial Park - Bridge',
    LoanAliasName: 'Metro Industrial Park',
    LoanAliasOptions: 'Metro Industrial Park,Metro Logistics Hub',
    InvestorName: 'TD Securities',
    LoanRanking: 3,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Standard late charge applies',
    UserUpdatedDate: '2026-03-15',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln6720',
    LoanCode: 'ln6720',
    LoanDescription: 'Yorkville Retail - 1st Mtg',
    LoanAliasName: 'Yorkville Retail',
    LoanAliasOptions: 'Yorkville Retail,Yorkville Mixed Use',
    InvestorName: 'RBC Capital Markets',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-02-22',
    Status: 'ACTIVE',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln4455',
    LoanCode: 'ln4455',
    LoanDescription: 'Scarborough Office - 2nd Mtg',
    LoanAliasName: 'Scarborough Office',
    LoanAliasOptions: 'Scarborough Office,Scarborough Plaza',
    InvestorName: 'BMO Capital Markets',
    LoanRanking: 2,
    DummyLoanIdentifier: true,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-02-08',
    Status: 'SETTLED',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln9083',
    LoanCode: 'ln9083',
    LoanDescription: 'North York Apartments - 1st Mtg',
    LoanAliasName: 'North York Apartments',
    LoanAliasOptions: 'North York Apartments,North York Tower',
    InvestorName: 'National Bank',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Waived per amendment 2025-12',
    UserUpdatedDate: '2026-01-30',
    Status: 'ACTIVE',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln3310',
    LoanCode: 'ln3310',
    LoanDescription: 'Mississauga Logistics - 1st Mtg',
    LoanAliasName: 'Mississauga Logistics',
    LoanAliasOptions: 'Mississauga Logistics,Mississauga Industrial',
    InvestorName: 'Scotiabank',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-01-18',
    Status: 'ACTIVE',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln7562',
    LoanCode: 'ln7562',
    LoanDescription: 'Oakville Medical Centre - 1st Mtg',
    LoanAliasName: 'Oakville Medical Centre',
    LoanAliasOptions: 'Oakville Medical Centre,Oakville Health Campus',
    InvestorName: 'Manulife Financial',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2025-12-05',
    Status: 'SETTLED',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln2189',
    LoanCode: 'ln2189',
    LoanDescription: 'Hamilton Mixed Use - Mezz',
    LoanAliasName: 'Hamilton Mixed Use',
    LoanAliasOptions: 'Hamilton Mixed Use,Hamilton Retail',
    InvestorName: 'Sun Life Financial',
    LoanRanking: 3,
    DummyLoanIdentifier: true,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Per Scott C, No Late Interest to be charged',
    UserUpdatedDate: '2025-11-20',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln8644',
    LoanCode: 'ln8644',
    LoanDescription: 'Waterloo Student Housing - 1st Mtg',
    LoanAliasName: 'Waterloo Student Housing',
    LoanAliasOptions: 'Waterloo Student Housing,Waterloo Campus Res',
    InvestorName: 'Desjardins Capital',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2025-10-14',
    Status: 'ACTIVE',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln5921',
    LoanCode: 'ln5921',
    LoanDescription: 'London Retail Portfolio - 2nd Mtg',
    LoanAliasName: 'London Retail Portfolio',
    LoanAliasOptions: 'London Retail Portfolio,London Mall Recap',
    InvestorName: 'HSBC Bank Canada',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Review annually',
    UserUpdatedDate: '2025-09-02',
    Status: 'SETTLED',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln5037',
    LoanCode: 'ln5037',
    LoanDescription: 'Brentwood Tower C - 1st Mtg',
    LoanAliasName: 'Brentwood Tower C',
    LoanAliasOptions: 'Brentwood Tower C,Brentwood Tower B,Brentwood Tower A',
    InvestorName: 'GMF Nominee Inc',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-04-16',
    Status: 'ACTIVE',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln0398',
    LoanCode: 'ln0398',
    LoanDescription: 'KingSett Mortgage LP No. 3 - 2nd Mtg',
    LoanAliasName: 'KingSett Mortgage LP No. 3',
    LoanAliasOptions: 'KingSett Mortgage LP No. 3,KingSett Mortgage LP No. 2',
    InvestorName: 'KingSett Real Estate Mortgage LP No. 3',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Per Scott C, No Late Interest to be charged',
    UserUpdatedDate: '2026-04-10',
    Status: 'ACTIVE',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln2841',
    LoanCode: 'ln2841',
    LoanDescription: 'Harbourfront Residences - 1st Mtg',
    LoanAliasName: 'Harbourfront Residences',
    LoanAliasOptions: 'Harbourfront Residences,Harbourfront Retail',
    InvestorName: 'CIBC World Markets',
    LoanRanking: 1,
    DummyLoanIdentifier: true,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-03-28',
    Status: 'SETTLED',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln1192',
    LoanCode: 'ln1192',
    LoanDescription: 'Metro Industrial Park - Bridge',
    LoanAliasName: 'Metro Industrial Park',
    LoanAliasOptions: 'Metro Industrial Park,Metro Logistics Hub',
    InvestorName: 'TD Securities',
    LoanRanking: 3,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Standard late charge applies',
    UserUpdatedDate: '2026-03-15',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln6720',
    LoanCode: 'ln6720',
    LoanDescription: 'Yorkville Retail - 1st Mtg',
    LoanAliasName: 'Yorkville Retail',
    LoanAliasOptions: 'Yorkville Retail,Yorkville Mixed Use',
    InvestorName: 'RBC Capital Markets',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-02-22',
    Status: 'ACTIVE',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln4455',
    LoanCode: 'ln4455',
    LoanDescription: 'Scarborough Office - 2nd Mtg',
    LoanAliasName: 'Scarborough Office',
    LoanAliasOptions: 'Scarborough Office,Scarborough Plaza',
    InvestorName: 'BMO Capital Markets',
    LoanRanking: 2,
    DummyLoanIdentifier: true,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-02-08',
    Status: 'SETTLED',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln9083',
    LoanCode: 'ln9083',
    LoanDescription: 'North York Apartments - 1st Mtg',
    LoanAliasName: 'North York Apartments',
    LoanAliasOptions: 'North York Apartments,North York Tower',
    InvestorName: 'National Bank',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Waived per amendment 2025-12',
    UserUpdatedDate: '2026-01-30',
    Status: 'ACTIVE',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln3310',
    LoanCode: 'ln3310',
    LoanDescription: 'Mississauga Logistics - 1st Mtg',
    LoanAliasName: 'Mississauga Logistics',
    LoanAliasOptions: 'Mississauga Logistics,Mississauga Industrial',
    InvestorName: 'Scotiabank',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-01-18',
    Status: 'ACTIVE',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln7562',
    LoanCode: 'ln7562',
    LoanDescription: 'Oakville Medical Centre - 1st Mtg',
    LoanAliasName: 'Oakville Medical Centre',
    LoanAliasOptions: 'Oakville Medical Centre,Oakville Health Campus',
    InvestorName: 'Manulife Financial',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2025-12-05',
    Status: 'SETTLED',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln2189',
    LoanCode: 'ln2189',
    LoanDescription: 'Hamilton Mixed Use - Mezz',
    LoanAliasName: 'Hamilton Mixed Use',
    LoanAliasOptions: 'Hamilton Mixed Use,Hamilton Retail',
    InvestorName: 'Sun Life Financial',
    LoanRanking: 3,
    DummyLoanIdentifier: true,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Per Scott C, No Late Interest to be charged',
    UserUpdatedDate: '2025-11-20',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln8644',
    LoanCode: 'ln8644',
    LoanDescription: 'Waterloo Student Housing - 1st Mtg',
    LoanAliasName: 'Waterloo Student Housing',
    LoanAliasOptions: 'Waterloo Student Housing,Waterloo Campus Res',
    InvestorName: 'Desjardins Capital',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2025-10-14',
    Status: 'ACTIVE',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln5921',
    LoanCode: 'ln5921',
    LoanDescription: 'London Retail Portfolio - 2nd Mtg',
    LoanAliasName: 'London Retail Portfolio',
    LoanAliasOptions: 'London Retail Portfolio,London Mall Recap',
    InvestorName: 'HSBC Bank Canada',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: 'Review annually',
    UserUpdatedDate: '2025-09-02',
    Status: 'SETTLED',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln5068',
    LoanCode: 'ln5068',
    LoanDescription: 'Tacofino',
    LoanAliasName: '',
    LoanAliasOptions: '',
    InvestorName: 'TD Securities',
    LoanRanking: 1,
    DummyLoanIdentifier: false,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-03-01',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln5560',
    LoanCode: 'ln5560',
    LoanDescription: 'Uptowns (Spruce Trails) 1st Mtg Purchase',
    LoanAliasName: '',
    LoanAliasOptions: '',
    InvestorName: 'CIBC World Markets',
    LoanRanking: 2,
    DummyLoanIdentifier: false,
    LateInterestApplicable: false,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-02-15',
    Status: 'ACTIVE',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln5672',
    LoanCode: 'ln5672',
    LoanDescription: 'Jordan (Heart Lake) Lands Receivership Loan',
    LoanAliasName: '',
    LoanAliasOptions: '',
    InvestorName: 'RBC Capital Markets',
    LoanRanking: 1,
    DummyLoanIdentifier: true,
    LateInterestApplicable: true,
    LateInterestOffNote: '',
    UserUpdatedDate: '2026-01-20',
    Status: 'DELINQUENT',
    UserUpdatedBy: 'rkaur',
  },
];
