import { SecurityValueApiRecord } from '../interfaces/security-value.interfaces';

/** Mock security value rows at loan-alias level until the live API is connected. */
export const SECURITY_VALUE_EXAMPLE_DATA: SecurityValueApiRecord[] = [
  {
    LoanKey: 'ln5037',
    LoanAliasName: 'Brentwood Tower C',
    CollateralPerYardi: 125_000_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'IN_DEFAULT',
    UserUpdatedDate: '2026-04-16',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln0398',
    LoanAliasName: 'KingSett Mortgage LP No. 3',
    CollateralPerYardi: 98_500_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'ACTIVE',
    UserUpdatedDate: '2026-04-10',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln2841',
    LoanAliasName: 'Harbourfront Residences',
    CollateralPerYardi: 210_750_000,
    SecurityValue: 210_750_000,
    SecurityValueOverridden: false,
    FundingStatus: 'SETTLED',
    UserUpdatedDate: '2026-03-28',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln1192',
    LoanAliasName: 'Metro Industrial Park',
    CollateralPerYardi: 67_200_000,
    SecurityValue: 72_000_000,
    SecurityValueOverridden: true,
    FundingStatus: 'IN_DEFAULT',
    UserUpdatedDate: '2026-03-15',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln6720',
    LoanAliasName: 'Yorkville Retail',
    CollateralPerYardi: 185_400_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'ACTIVE',
    UserUpdatedDate: '2026-02-22',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln4455',
    LoanAliasName: 'Scarborough Office',
    CollateralPerYardi: 54_800_000,
    SecurityValue: 54_800_000,
    SecurityValueOverridden: false,
    FundingStatus: 'SETTLED',
    UserUpdatedDate: '2026-02-08',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln9083',
    LoanAliasName: 'North York Apartments',
    CollateralPerYardi: 142_300_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'FUNDED',
    UserUpdatedDate: '2026-01-30',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln3310',
    LoanAliasName: 'Mississauga Logistics',
    CollateralPerYardi: 88_950_000,
    SecurityValue: 95_000_000,
    SecurityValueOverridden: true,
    FundingStatus: 'IN_DEFAULT',
    UserUpdatedDate: '2026-01-18',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln7721',
    LoanAliasName: 'Etobicoke Mixed Use',
    CollateralPerYardi: 76_500_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'DELINQUENT',
    UserUpdatedDate: '2025-12-12',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln5589',
    LoanAliasName: 'Waterfront Plaza',
    CollateralPerYardi: 312_000_000,
    SecurityValue: 300_000_000,
    SecurityValueOverridden: true,
    FundingStatus: 'IN_DEFAULT',
    UserUpdatedDate: '2025-11-30',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln2244',
    LoanAliasName: 'Liberty Village Condos',
    CollateralPerYardi: 163_750_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'COMMITTED',
    UserUpdatedDate: '2025-11-05',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln6612',
    LoanAliasName: 'Oakville Corporate Centre',
    CollateralPerYardi: 91_200_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'ACTIVE',
    UserUpdatedDate: '2025-10-20',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln9934',
    LoanAliasName: 'Hamilton Industrial Hub',
    CollateralPerYardi: 48_600_000,
    SecurityValue: 48_600_000,
    SecurityValueOverridden: false,
    FundingStatus: 'SETTLED',
    UserUpdatedDate: '2025-10-01',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln1188',
    LoanAliasName: 'Markham Tech Campus',
    CollateralPerYardi: 134_500_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'IN_DEFAULT',
    UserUpdatedDate: '2025-09-14',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln4477',
    LoanAliasName: 'Richmond Hill Retail',
    CollateralPerYardi: 59_300_000,
    SecurityValue: 62_500_000,
    SecurityValueOverridden: true,
    FundingStatus: 'FUNDED',
    UserUpdatedDate: '2025-08-22',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln8820',
    LoanAliasName: 'Brampton Distribution',
    CollateralPerYardi: 41_800_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'ACTIVE',
    UserUpdatedDate: '2025-08-01',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln3355',
    LoanAliasName: 'Vaughan Medical Centre',
    CollateralPerYardi: 102_400_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'COMMITTED',
    UserUpdatedDate: '2025-07-19',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln7099',
    LoanAliasName: 'Pickering Power Centre',
    CollateralPerYardi: 73_900_000,
    SecurityValue: 73_900_000,
    SecurityValueOverridden: false,
    FundingStatus: 'SETTLED',
    UserUpdatedDate: '2025-07-02',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln5522',
    LoanAliasName: 'Ajax Residential Phase 2',
    CollateralPerYardi: 56_100_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'IN_DEFAULT',
    UserUpdatedDate: '2025-06-11',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln8144',
    LoanAliasName: 'Whitby Office Tower',
    CollateralPerYardi: 84_250_000,
    SecurityValue: 90_000_000,
    SecurityValueOverridden: true,
    FundingStatus: 'DELINQUENT',
    UserUpdatedDate: '2025-05-28',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln2666',
    LoanAliasName: 'Newmarket Shopping',
    CollateralPerYardi: 38_700_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'ACTIVE',
    UserUpdatedDate: '2025-05-10',
    UserUpdatedBy: 'jsmith',
  },
  {
    LoanKey: 'ln4011',
    LoanAliasName: 'Barrie Lakeside',
    CollateralPerYardi: 62_400_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'FUNDED',
    UserUpdatedDate: '2025-04-22',
    UserUpdatedBy: 'alee',
  },
  {
    LoanKey: 'ln9333',
    LoanAliasName: 'Guelph University Lands',
    CollateralPerYardi: 115_800_000,
    SecurityValue: 118_000_000,
    SecurityValueOverridden: true,
    FundingStatus: 'IN_DEFAULT',
    UserUpdatedDate: '2025-04-03',
    UserUpdatedBy: 'mchen',
  },
  {
    LoanKey: 'ln1777',
    LoanAliasName: 'Kitchener Innovation District',
    CollateralPerYardi: 79_600_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'COMMITTED',
    UserUpdatedDate: '2025-03-15',
    UserUpdatedBy: 'rkaur',
  },
  {
    LoanKey: 'ln6288',
    LoanAliasName: 'Waterloo Student Housing',
    CollateralPerYardi: 44_200_000,
    SecurityValue: null,
    SecurityValueOverridden: false,
    FundingStatus: 'ACTIVE',
    UserUpdatedDate: '2025-02-28',
    UserUpdatedBy: 'jsmith',
  },
];
